export * from './HttpError';
import { ErrorMessagesEnum } from './ErrorMessagesEnum';
export const {
  INVALID_PASSWORD,
  NOT_FOUNDED,
  INVALID_TOKEN,
  FAIL_TOKEN_GENERATION,
  INVALID_USER_ID,
  INVALID_USER_EMAIL,
  SUCCESSFUL_OPERATION,
  NOT_AUTHORIZATED,
  ALREADY_EXISTING_USER,
  REQUIRED_REGISTER_FIELDS_NOT_FILLED,
} = ErrorMessagesEnum;
